# Generated by Django 5.2.10 on 2026-03-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_userlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='is_working',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='work_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
