# Generated by Django 5.2.10 on 2026-03-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_locationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
