# Generated by Django 5.2.10 on 2026-03-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_userlocation_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
